import Home from "./User/Home"
import Checkout from './User/Checkout'
import Pay from './User/Pay'
import Purchase from './User/Purchase'
import WomenProducts from './User/Women/WomenProducts'
import ProductDetail from "./User/ProductDetail"
import WTshirts from './User/Women/WTshirts'
import WShirts from './User/Women/WTshirts'
import WTrousers from './User/Women/WTrousers'
import MenProducts from './User/Men/MenProducts'
import MTshirts from './User/Men/MTshirts'
import MTrousers from './User/Men/MTrousers'
import MShirts from './User/Men/MShirts'
import Products from './Admin/Products'
import Login from './Admin/Login'
import Panel from "./Admin/Panel"
import Stock from "./Admin/Stock"
import Orders from "./Admin/Orders"
export{Home,Checkout,Pay,Purchase,WomenProducts,WShirts,WTrousers,WTshirts,MenProducts,MShirts,MTrousers,MTshirts,Products,Login,Panel,Stock,Orders,ProductDetail}